language: node_js
node_js:
- '5'
cache:
  directories:
  - node_modules
script:
- npm run test
before_install:
- openssl aes-256-cbc -K $encrypted_0851764f2c15_key -iv $encrypted_0851764f2c15_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host bygis.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - cd deploy && tar czf - * | ssh bygis@bygis.com 'cat > foxgis.tar.bz2'
  - ssh bygis@bygis.com 'bzip2 -dkc foxgis.tar.bz2 | tar -xf - -C ./judy/public'
